branch-defaults:
  default:
    environment: dev-env
  master:
    environment: empire-api
environment-defaults:
  dev-env:
    branch: null
    repository: null
global:
  application_name: empire-api
  default_ec2_keyname: null
  default_platform: Go
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
